### ISSUE TITLE
Temporary AWS credential problem

### ISSUE THREAD

**Issue by leoCamilo** [godatadriven-dockerhub/pyspark#13]
Hello, this is more a question then an issue, it's possible to update the Hadoop version?

My idea is to use the image in a AWS ECS Task to transform s3 data, I've managed to add boto3 into the image and I can get all kind of credentials, but to use in pyspark I should use like this:

```
hadoop_cfg.set("fs.s3a.aws.credentials.provider", "org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider")
hadoop_cfg.set("fs.s3a.session.token", credentials.token)
hadoop_cfg.set("fs.s3a.access.key", credentials.access_key)
hadoop_cfg.set("fs.s3a.secret.key", credentials.secret_key)
```

After a long search I found that this only works on Hadoop 2.8+ (actually, spark and Hadoop are really bad managing dependencies, one thing only works with the exact version of other jdk), so the question is if is possible that the Hadoop version could be a parameter or an environment variable for cases like this.

**Comment by dardanbekteshi** [comment]
@leoCamilo I have had some similar issues with Amazon S3 when trying to run this image locally. Similar to your findings, I found out there were some weird dependency issues with Hadoop, Spark, JDK etc. So my original goal was to make this image use AWS credentials via an AWS profile, but that failed. You are doing something similar since you are trying to use `session.token` etc.

What I ended up doing was to use good-old AWS access key and AWS secret access key. In particular:
```
# modify these to point to the (AWS) service account's credentials
AWS_ACCESS_KEY_ID=<access-key-goes-here>
AWS_SECRET_ACCESS_KEY=<secret-key-goes-here>
```
So you need to create an AWS IAM user first which has access to the S3 buckets which are relevant for your task. Then, just set up these two environment variables in your ECS image and it should work. Note that with this setup you do not need to add/modify any of the hadoop or spark configuration, this simple SparkSession should work:
```
    spark_session = SparkSession.builder \
        .appName("MyApp") \
        .getOrCreate()
```

**Comment by leoCamilo** [comment]
Hey @dardanbekteshi, thanks for the suggestion, I manage to solve in a very similar way, first, I don't know if you're familiar but you can simulate the AWS ECS environment locally ([tutorial](https://aws.amazon.com/blogs/compute/a-guide-to-locally-testing-containers-with-amazon-ecs-local-endpoints-and-docker-compose/)) even with roles, and since the only solution was access_key and secret_access_key, what I did was:

- created a user with only s3 permissions in IAM like you
- saved the credentials at parameter store
- and the container has a role for parameter store read only

So I can read and set the credentials with boto3 at the start of the task, The advantage is not have credential info as clean text at the IaC repository or the cloud console.

**Comment by dardanbekteshi** [comment]
@leoCamilo thanks for sharing your solution. Always a good idea to avoid using clean text credentials :) What I meant with env variables is to use some mapping solution from SecretsManager (or parameter store) with the container. At least that is how we use SecretsManager with Kubernetes. The secrets are stored in SecretsManager but they are synced into Kubernetes Secrets and then they are available to the containers in the form of env variables. We use the [Kubernetes External Secrets](https://github.com/external-secrets/kubernetes-external-secrets) for that. Not sure if ECS has a similar functionality.
